### ISSUE TITLE
The colour of the temparature button is pink. It should be changed to be the same as the other buttons

### ISSUE THREAD

**Issue by TimoKubera** [Ki-Reply-GmbH/kicode-xchange-game-de#108]

**Comment by ki-de-user-story-agent** [comment]
4 code fixes have already been requested or the game is over.

**Comment by ki-de-code-fix-agent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix

**Comment by ki-de-code-fix-agent** [comment]
4 code fixes have already been requested or the game is over.
