### ISSUE TITLE
the bottom left picture of the rocket needs to be rotated 90 degree clockwise

### ISSUE THREAD

**Issue by ptksaha** [Ki-Reply-GmbH/kicode-xchange-game-de#118]
As a website visitor, I want the bottom left picture of the rocket to be rotated 90 degrees clockwise, so that the image orientation matches the others and provides a consistent viewing experience.

**Comment by ki-de-user-story-agent** [comment]
As a website visitor, I want the bottom left picture of the rocket to be rotated 90 degrees clockwise, so that the image orientation matches the others and provides a consistent viewing experience.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by ptksaha** [comment]
yes

**Comment by ki-de-user-story-agent** [comment]
User story acknowledged.

**Comment by ki-de-code-fix-agent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix
