### ISSUE TITLE
Change the pink button so it's color matches the others

### ISSUE THREAD

**Issue by ptksaha** [Ki-Reply-GmbH/kicode-xchange-game-de#134]
As a website user, I want all the buttons to have consistent coloring, so that the interface looks unified and visually appealing.

**Comment by ki-de-user-story-agent** [comment]
As a website user, I want all the buttons to have consistent coloring, so that the interface looks unified and visually appealing.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by ptksaha** [comment]
yes

**Comment by ki-de-user-story-agent** [comment]
User story acknowledged.

**Comment by ki-de-code-fix-agent** [comment]
Code Fix agent was unable to perform the fixes. Please re-create the issue with more detail.
