### ISSUE TITLE
The temparature button should be changed from pink to orange like the other buttons

### ISSUE THREAD

**Issue by funkela** [Ki-Reply-GmbH/kicode-xchange-game-de#17]

**Comment by ki-de-user-story-agent** [comment]
As a website user, I want the temperature button to be changed from pink to orange to match the other buttons, so that the website has a consistent and uniform design language.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by funkela** [comment]
Please remove the colour orange and make it in the way of the other buttons.

**Comment by ki-de-user-story-agent** [comment]
As a website user, I want the temperature button to match the style and color of the other buttons to ensure a consistent and uniform design across the website.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.
